BooksLife.Web/Models/Book/AddBookViewModel.cs
using BooksLife.Core;
using System.ComponentModel.DataAnnotations;

namespace BooksLife.Web
{
    public class AddBookViewModel
    {
        [Required]
        public string Title { get; set; } = string.Empty;
        [Required]
        public Guid AuthorId { get; set; }
        public int PublicationYear { get; set; }
        public int EditionPublicationYear { get; set; }
        [Required]
        public BookCondition Condition { get; set; }
        public string? ConditionNote { get; set; } = string.Empty;
    }
}

BooksLife.Web/Models/Book/BookViewModel.cs
using BooksLife.Core;

namespace BooksLife.Web
{
    public class BookViewModel
    {
        public bool IsBorrowed { get; set; } = false;
        public Guid Id { get; set; }
        public string? Title { get; set; } = string.Empty;
        public int PublicationYear { get; set; }
        public int EditionPublicationYear { get; set; }
        public string AuthorName { get; set; } = string.Empty;
        public BookCondition Condition { get; set; }
        public string? ConditionNote { get; set; } = string.Empty;
    }
}

BooksLife.Web/Models/BookViewModel.cs
using BooksLife.Core;
using System.ComponentModel.DataAnnotations;

namespace BooksLife.Web
{
    public class BookViewModel
    {
        public bool IsBorrowed { get; set; } = false;
        public Guid Id { get; set; }
        public string? Title { get; set; } = string.Empty;
        [Required]
        public Guid BookTitleId { get; set; }
        public int PublicationYear { get; set; }
        [Required]
        public int EditionPublicationYear { get; set; }
        public string AuthorName { get; set; } = string.Empty;
        public Guid AuthorId { get; set; }
        [Required]
        public BookCondition Condition { get; set; }
        public string? ConditionNote { get; set; } = string.Empty;
    }
}

BooksLife.Web/Controllers/AuthorController.cs
using AutoMapper;
using BooksLife.Core;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BooksLife.Web
{
    public class AuthorController : Controller
    {
        private readonly IAuthorManager _authorManager;
        private readonly IMapper _mapper;

        public AuthorController(IAuthorManager authorManager, IMapper mapper)
        {
            _authorManager = authorManager;
            _mapper = mapper;
        }

        public IActionResult List(int? page, string? filterString = null, Response? response = null)
        {
            ViewBag.Response = response;
            ViewBag.FilterString = filterString;

            int pageSize = 10;
            int pageNumber = page ?? 1;

            var authorDtos = _authorManager.GetPage(pageSize, pageNumber, filterString, out int totalCount);
            var authorViewModels = _mapper.Map<List<AuthorViewModel>>(authorDtos);

            var pagedList = new StaticPagedList<AuthorViewModel>(authorViewModels, pageNumber, pageSize, totalCount);

            return View(pagedList);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddAuthorViewModel authorViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(authorViewModel);
            }

            var authorDto = _mapper.Map<AddAuthorDto>(authorViewModel);
            var response = _authorManager.Add(authorDto);
            return RedirectToAction("List", response);
        }

        public IActionResult Remove(Guid id)
        {
            var response = _authorManager.Remove(id);
            return RedirectToAction("List", response);
        }
    }
}

BooksLife.Web/Controllers/BookController.cs
using AutoMapper;
using BooksLife.Core;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BooksLife.Web
{
    public class BookController : Controller
    {
        private readonly IBookManager _bookManager;
        private readonly IAuthorManager _authorManager;
        private readonly IMapper _mapper;

        public BookController(IBookManager bookManager, IAuthorManager authorManager, IMapper mapper)
        {
            _bookManager = bookManager;
            _authorManager = authorManager;
            _mapper = mapper;
        }

        public IActionResult Index(Guid id)
        {
            var bookDto = _bookManager.Get(id);
            var bookViewModel = _mapper.Map<BookViewModel>(bookDto);
            return View(bookViewModel);
        }

        public IActionResult Add()
        {
            var authorDtos = _authorManager.GetAll();
            ViewBag.Authors = _mapper.Map<List<AuthorViewModel>>(authorDtos);
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddBookViewModel bookViewModel)
        {
            if (!ModelState.IsValid)
            {
                var authorDtos = _authorManager.GetAll();
                ViewBag.Authors = _mapper.Map<List<AuthorViewModel>>(authorDtos);
                return View(bookViewModel);
            }

            var bookDto = _mapper.Map<AddBookDto>(bookViewModel);
            var result = _bookManager.Add(bookDto);
            return RedirectToAction("List", result);
        }

        public IActionResult List(int? page, string? filterString = null, Response? response = null)
        {
            ViewBag.Response = response;
            ViewBag.FilterString = filterString;

            int pageSize = 10;
            int pageNumber = page ?? 1;

            var bookDtos = _bookManager.GetPage(pageSize, pageNumber, filterString, out int totalCount);
            var bookViewModels = _mapper.Map<List<BookViewModel>>(bookDtos);
            var pagedList = new StaticPagedList<BookViewModel>(bookViewModels, pageNumber, pageSize, totalCount);

            return View(pagedList);
        }

        public IActionResult Remove(Guid id)
        {
            var response = _bookManager.Remove(id);
            return RedirectToAction("List", response);
        }
    }
}

BooksLife.Web/Views/Book/Add.cshtml
@using BooksLife.Core;
@model AddBookViewModel
@{
    ViewData["Title"] = "Add a new book";
}

<h1>Add a new title</h1>

<form asp-controller="Book" asp-action="Add" class="mt-5">
    <div class="container">
        <div class="row mb-3">
            <div class="form-group col-md-4">
                <label for="Title">Title</label>
                <input type="text" class="form-control" id="Title" placeholder="Title" name="Title" />
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.Title)</small>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="form-group col-md-4">
                <label for="PublicationYear">Year of publication</label>
                <input type="number" class="form-control" id="PublicationYear" placeholder="PublicationYear" name="PublicationYear" />
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.PublicationYear)</small>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="form-group col-md-4">
                <label for="AuthorId">Author</label>
                <select class="form-control" id="AuthorId" name="AuthorId">
                @if(ViewBag.Authors is not null)
                {
                    foreach (var author in ViewBag.Authors as List<AuthorViewModel>)
                    {
                        <option value="@author.Id">@author.Firstname @author.Lastname</option>
                    }
                }

                </select>
                <a asp-controller="Author" asp-action="List" class="text-decoration-underline text-primary">Manage authors</a>
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.AuthorId)</small>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="form-group col-md-6">
                <label for="EditionPublicationYear">Year of edition publication</label>
                <input type="number" class="form-control" id="EditionPublicationYear" placeholder="Year of edition publication" name="EditionPublicationYear" />
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.EditionPublicationYear)</small>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="form-group col-md-6">
                <label for="Condition">Condition</label>
                <select class="form-control" id="Condition" name="Condition">
                    <option value="@BookCondition.Poor">@BookCondition.Poor.ToString()</option>
                    <option value="@BookCondition.Fair">@BookCondition.Fair.ToString()</option>
                    <option value="@BookCondition.Good">@BookCondition.Good.ToString()</option>
                    <option value="@BookCondition.Fine">@BookCondition.Fine.ToString()</option>
                </select>
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.Condition)</small>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="form-group col-md-6">
                <label for="ConditionNote">Condition note</label>
                <input type="text" class="form-control" id="ConditionNote" placeholder="Condition note" name="ConditionNote" />
                <div class="text-danger">
                    <small>@Html.ValidationMessageFor(x => x.ConditionNote)</small>
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success ms-2">Submit</button>
</form>

BooksLife.Web/Views/Book/Index.cshtml
@model BookViewModel
@if(Model is not null)
{
    ViewData["Title"] = Model.Title;

    <h1>
        @Model.Title (@Model.EditionPublicationYear)
        <a class="btn btn-sm transparent" title="Remove" asp-controller="Book" asp-action="Remove" asp-route-id="@Model.Id">
            <i class="bi bi-trash text-danger h4"></i>
        </a>
    </h1>
    <small class="text-secondary">@Model.Id</small>

    <hr />

    <div class="container">
        <div class="row mb-3">
            <div class="form-group col-md-6">
                <label class="text-secondary" for="Author">Author</label>
                <p id="Author">@Model.AuthorName</p>
            </div>
            <div class="form-group col-md-6">
                <label class="text-secondary" for="Condition">Condition</label>
                <p id="Condition">@Model.Condition.ToString()</p>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <label class="text-secondary" for="PublicationYear">Year of publication</label>
                <p id="PublicationYear">@Model.PublicationYear</p>
            </div>
            <div class="col-md-6">
                <label class="text-secondary" for="ConditionNote">Condition note</label>
                <p id="ConditionNote">@(string.IsNullOrEmpty(Model.ConditionNote) ? "-" : Model.ConditionNote)</p>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <label class="text-secondary" for="EditionPublicationYear">Year of edition publication</label>
                <p id="EditionPublicationYear">@Model.EditionPublicationYear</p>
            </div>
        </div>
    </div>

    <hr />
}

BooksLife.Web/Views/Book/List.cshtml
@using BooksLife.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@model IPagedList<BookViewModel>;

@if (Model is not null)
{
    ViewData["Title"] = "List of Books";

    @if (!(ViewBag.Response.Message == ""))
    {
        <div class="alert @(ViewBag.Response.Succeed ? "alert-success" : "alert-danger")">
            @ViewBag.Response.Message
        </div>
    }

    <h1>List of books</h1>

    <hr />

    <a class="text-success fw-bold text-decoration-none float-start mt-1" asp-controller="Book" asp-action="Add"><small>+ Add new</small></a>
    <form asp-controller="Book" asp-action="List">
        <div class="input-group w-25 float-end">
            <input type="text" class="form-control" placeholder="Search by title" aria-label="search" aria-describedby="search-button" name="filterString" value="@ViewBag.FilterString">
            <button type="submit" class="btn btn-outline-secondary" id="search-button"><i class="bi bi-search"></i></button>
        </div>
    </form>


    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th>Title</th>
                <th>Year of publication</th>
                <th>Year of edition publication</th>
                <th>Author <a asp-controller="Author" asp-action="List" class="text-primary"><i class="bi bi-pencil-square" title="Manage authors"></i></a></th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.PublicationYear</td>
                    <td>@book.EditionPublicationYear</td>
                    <td>@book.AuthorName</td>
                    <td>
                        <a class="btn btn-sm transparent" title="Show details" asp-controller="Book" asp-action="Index" asp-route-id="@book.Id">
                            <i class="bi bi-info-circle text-primary"></i>
                        </a>
                        <a class="btn btn-sm transparent" title="Remove" asp-controller="Book" asp-action="Remove" asp-route-id="@book.Id">
                            <i class="bi bi-trash text-danger"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


    <p class="float-end">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
    <div class="d-flex justify-content-center">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("List", new { page, ViewBag.FilterString }), new PagedListRenderOptions{
            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" }
        })
    </div>

}